version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-store
    environment:
      MYSQL_ROOT_PASSWORD: y3k$9Xt#bR!sD@rK!
      MYSQL_DATABASE: storeDb
      MYSQL_USER: userdbstore
      MYSQL_PASSWORD: y3k$9Xt#bR!sD@rK!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      network-db-ms:
        aliases:
          - network_ms

  # sql-server:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: sql-server-store
  #   environment:
  #     SA_PASSWORD: y3k$9Xt#bR!sD@rK!
  #     ACCEPT_EULA: Y
  #   ports:
  #     - "1433:1433"
    # networks:
    #   network-db-ms:
    #     aliases:
    #       - network_ms

  ms-store:
    image: joallyzg/ms-store
    container_name: ms-store
    ports:
      - "8080:8080"
    depends_on:
      # - sql-server
      - mysql
    networks:
      network-db-ms:
        aliases:
          - network_db_mysql
    environment:
      #SPRING_DATASOURCE_URL: jdbc:sqlserver://sql-server:1433;databaseName=storeDb;
      #SPRING_DATASOURCE_USERNAME: sa
      #SPRING_DATASOURCE_PASSWORD: y3k$9Xt#bR!sD@rK!
      MYSQL_DATASOURCE_URL: jdbc:mysql://mysql:3306/storeDb
      MYSQL_USER: userdbstore
      MYSQL_PASSWORD: y3k$9Xt#bR!sD@rK!

  app-store:
    image: joallyzg/app-store
    container_name: app-store
    ports:
        - "3000:3000"
    depends_on:
        - nginx-server

  nginx-server:
    image: nginx:alpine
    container_name: nginx-store
    volumes:
        - ./build:/usr/share/nginx/html
    ports:
        - "81:80"
networks:
  network-db-ms:
    name: net-db-ms
    driver: bridge
    ipam: 
       driver: default

volumes:
  mysql_data: